spring.application.name=liftoff

# Virtual Threads (Spring Boot 4 + Java 21)
spring.threads.virtual.enabled=true

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/liftoff
spring.datasource.username=liftoff
spring.datasource.password=5766

# Flyway
spring.flyway.enabled=true

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate

# JWT Configuration
jwt.secret=0b014818d06e816b95e11d5fa4ff1f427c86f02698f286b4916297e09fa1adcb
jwt.access-token.expiration=900000
jwt.refresh-token.expiration=604800000  