spring.application.name=liftoff

# Virtual Threads (Spring Boot 4 + Java 21)
spring.threads.virtual.enabled=true

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/liftoff
spring.datasource.username=liftoff
spring.datasource.password={your password}

# Flyway
spring.flyway.enabled=true

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate

# JWT Configuration
jwt.secret={your_super_secure_key}
jwt.access-token.expiration=900000
jwt.refresh-token.expiration=604800000  
